<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Tmilos\\Value\\Tests\\' => array($vendorDir . '/tmilos/value/tests'),
    'Tmilos\\Value\\' => array($vendorDir . '/tmilos/value/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'ForceUTF8\\' => array($vendorDir . '/neitanod/forceutf8/src'),
);
